'use strict';

window.QT_GUIDE = {
  schemaVersion: 2,
  title: 'When Your Life Still Works But No Longer Fits',
  stages: [
    {
      id: 'fog', number: 1, name: 'Fog', line: 'Not knowing is the starting point',
      entry: [
        'Something deserves your attention. That is all Fog asks you to know.',
        'The signal may be tiredness, anger, envy, flatness, a changed role, a loss, a difficult season or an external situation that is no longer workable. It may point towards change. It may point towards support, time, rest or a truth you cannot yet interpret. Fog does not decide.',
        'Across the next three chapters, you will examine the stories attached to midlife, the bargains hidden inside familiarity and competence, and the different voices within you. The purpose is not to find the right explanation. It is to notice more of what is actually present before one explanation becomes the verdict.'
      ],
      arrival: 'What has made you pause here now?',
      transition: {
        explored: ['You began with a signal rather than an explanation. You considered the stories attached to age and change, the shelter and cost inside familiarity, and the information carried by different inner responses.', 'You may understand the original unease differently. You may not. Fog has done its work if more than one honest explanation remains available and the first story has not been allowed to become the verdict too quickly.'],
        next: 'Filter asks what happens when many things compete for limited attention: habit, responsibility, other people’s needs, recurring thoughts, practical facts and signals from within. Its purpose is not to silence them. It is to distinguish among them.'
      },
      chapters: [
        {
          n: 1, title: 'The Myth of Midlife Decline',
          entry: ['A stage of life can contain gain, loss, continuity, constraint and possibility at the same time.', 'This chapter challenged two stories that are too small: that midlife is simple decline, and that every difficult transition must become reinvention or empowerment. This activity gives your actual experience more room than either story allows.'],
          primary: { kind: 'Map', title: 'What this stage of life gives and takes', intro: ['Choose the life stage or transition that is most present for you now. Add as much as belongs on either side. Do not force balance. A loss does not need a compensating benefit, and a possibility does not cancel what has become harder.'], fields: ['Harder, changed or less available', 'Possible, visible or newly available', 'Still fitting or still worth its cost'], repeatable: true, noteLabel: 'What part of this experience does neither side contain?' },
          optional: { kind: 'Reflect', title: 'Further reflection', fields: ['Which story about age or this transition has been shaping what you allow yourself to see?', 'What loss deserves to be named without being redeemed?', 'Is there a possibility you have dismissed mainly because of age, timing or an inherited expectation?', 'What did you once choose sincerely that you now experience differently?'] },
          landing: 'Does your account contain a fact you had been minimising, a cultural story that no longer fits, or a loss that needs room rather than reframing?',
          positions: 'Save and stop; leave the account open; return after more time; gather practical information about one possibility. No action is required.'
        },
        {
          n: 2, title: 'The Comfort Zone Trap',
          entry: ['The familiar may shelter you and constrain you. Competence may give you trust and quietly become the reason more is expected.', 'This is not an invitation to disrupt a life because it is familiar. It is a closer look at the arrangement: what keeps it working, who relies on it, how it is subsidised and which assumptions have actually been tested.'],
          primary: { kind: 'Map', title: 'The arrangement around staying and changing', intro: ['Choose one routine, responsibility, role or arrangement that you are questioning.'], fields: ['What does staying protect or make possible?', 'What does staying continue to cost?', 'What might changing, reducing or sharing it make possible?', 'What might changing cost, and who would carry that cost?', 'Which parts are fixed, negotiable, shareable or simply assumed?', 'What has looked easy because you supplied time, sleep, money, emotional labour or hidden effort?'] },
          optional: { kind: 'Try This', title: 'A small test for a live uncertainty', intro: ['Use this only if a small reversible action can answer a real question.'], fields: ['What am I uncertain about?', 'What small change could produce useful evidence without creating disproportionate consequence?', 'What will I notice before, during and afterwards?', 'What would count as no useful change?', 'When will I review what happened?'], experiment: true, outro: 'The test does not have to produce movement. It may strengthen the case for staying, changing, renegotiating or waiting.' },
          landing: 'Which parts of the arrangement are facts, which are predictions, and which have survived because no one has had to examine them? Is anyone else’s reliance or constraint missing from the map?',
          positions: 'Save and stop; test one assumption; gather information; prepare a conversation; make a conscious yes for now; leave the question open.'
        },
        {
          n: 3, title: 'Meeting Your Inner Voice',
          entry: ['There may be several voices, and they may disagree for good reason.', 'Your first response can reveal something later thought edits out. Later thought can add evidence, context and consequence that the first response did not contain. Neither must win automatically. This activity records the movement between them.'],
          primary: { kind: 'Record', title: 'First response and later commentary', intro: ['Choose one moment from today or a recent decision.'], fields: ['What happened?', 'What was my first response?', 'What did later commentary add, remove or predict?', 'What evidence supports or challenges those responses?', 'What, if anything, do I know now?'], allowUnknown: true },
          optional: { kind: 'Map', title: 'When several voices are active', intro: ['Add one row for each distinct voice or claim. Do not identify an “authentic” winner. A calm voice is not automatically wiser, and a frightened one is not automatically wrong.'], fields: ['What does it say?', 'What is it noticing or predicting?', 'What history or present condition may be informing it?', 'What evidence does it carry?', 'What weight does it deserve for now?'], repeatable: true },
          landing: 'Have you learned something about the situation, or only about the volume or tone of a response? Is there a prediction that can be checked? Is there a real risk or present condition that needs attention?',
          positions: 'Save and stop; gather evidence; return after the event; make a provisional judgement; leave the voices unresolved.'
        }
      ]
    },
    {
      id: 'filter', number: 2, name: 'Filter', line: 'You can’t see clearly through everything',
      entry: ['Fog helped you notice without forcing an explanation. You may now be more aware of how much is present: recurring thoughts, alerts, roles, responsibilities, old habits, other people’s knowledge and needs, and the conditions of the life around you.', 'Filter is not about calling all of that noise. Much of it matters. The work is to create enough room to ask: what needs attention now, what can wait, what belongs to me, what belongs to somebody else, and what does the situation itself require?', 'The next three chapters use attention, boundaries around access and realistic white space to make those distinctions more possible. Quiet may bring relief. It may also reveal something difficult. Neither outcome is required.'],
      arrival: 'What feels hardest to distinguish at present?',
      transition: { explored: ['You looked at attention as contact rather than calm, at the full arrangement around a yes or no, and at space as room for what is present rather than a guarantee of clarity.', 'Filtering does not remove responsibility, other people’s knowledge or difficult facts. It helps you see which claim you are meeting and why. What emerges may still compete.'], next: 'Focus examines what happens when several worthwhile things matter and a finite life cannot give everything everything. The next work is not to discover one perfect priority, but to understand the claims, costs and consequences inside actual choices.' },
      chapters: [
        { n: 4, title: 'Mindfulness Isn’t a Buzzword', entry: ['Attention is not a performance of calm. It is a way of noticing where you are and deciding what the next moment requires.', 'Use this short practice when you realise that your mind is in replay, prediction or another conversation. Adapt it, keep your eyes open, move or stop if close attention makes things worse.'], primary: { kind: 'Try This', title: 'Return to one present fact', intro: ['1. Name the destination. Where had your attention gone?', '2. Notice without diagnosing. What is your body doing, if body attention is useful to you? Alternatively, name three things you can see or hear.', '3. Return to one present fact. The words on the screen, the temperature of a mug, the person speaking, the ground under your feet.', '4. Choose what happens next. Continue; pause; make a note; check evidence; attend to what the thought may be signalling; seek support.'], fields: ['What was happening before the practice?', 'What did the pause make more visible?', 'What, if anything, now needs a response?'], quickOptions: ['Nothing changed', 'This practice did not help'] }, landing: 'Was the returning thought replay, prediction, present information or some mixture? Is the issue inside your attention, outside you in the situation, or across both?', positions: 'Return to the task; record for later; check the facts; act on an external problem; stop the practice; seek appropriate support.' },
        { n: 5, title: 'The Quiet “No”', entry: ['A boundary is a decision with consequences, not a performance of bravery.', 'An automatic yes often buys something: approval, peace, identity, care for another person or protection from a harder conversation. Changing it may redistribute work, emotion or inconvenience. This activity looks at the whole arrangement before asking for a new answer.'], primary: { kind: 'Map', title: 'A boundary audit', intro: ['Choose one recurring commitment or request.'], fields: ['What am I giving: time, money, attention, emotional labour, availability or something else?', 'What does this commitment protect or make possible?', 'What is its present cost to me and to others?', 'If I reduced, shared or stopped it, what would move and to whom?', 'Which consequence am I most afraid of?', 'What power, dependency, care or safety conditions affect my freedom to choose?', 'What responsibility would remain mine whatever I decide?'] }, optional: { kind: 'Reflect', title: 'Make room before the answer', fields: ['Draft a pause, not necessarily a refusal. What do you need to check? What part could you offer? What information would help the other person understand the real constraint? Are you explaining to inform, or continuing until you receive permission?'], outro: 'Use as much space as you need. There is no prescribed sentence or “no explanation”.' }, landing: 'Is the discomfort old conditioning, grief about a limit, anticipated harm, a value in conflict, or evidence that your decision needs reconsideration? Has new information appeared, or are you meeting a cost you already expected?', positions: 'Conscious yes; no; reduction; renegotiation; gather support or advice; delay the answer; leave open.', support: 'Where coercion or material risk is present, preparation and specialist support take priority over confrontation.' },
        { n: 6, title: 'Creating White Space', entry: ['Space does not promise calm. It allows what was crowded out to become more visible.', 'Some fullness is habitual; some is structural. The available room may be an afternoon, seven minutes or a conversation in which you do not have to look on the bright side. A small gap can matter without being treated as sufficient when the life needs more support.'], primary: { kind: 'Map', title: 'Give an open matter a place', intro: ['Add any unresolved matter that is repeatedly returning to attention. Place it provisionally under:', 'Act — there is a next step I can take.', 'Wait — the next information or opportunity belongs to another person or to time.', 'Carry — no action will remove this reality, but it deserves acknowledgement.', 'Rows can be moved later without losing their notes.'], fields: ['Position: Act, Wait or Carry', 'What is still active here?', 'What would stop me rehearsing it continuously?'], repeatable: true }, optional: { kind: 'Reflect', title: 'Five minutes between things', intro: ['If the day allows it, leave a small gap between two roles or tasks.'], fields: ['What am I carrying from what just ended?', 'What does the next thing actually require?', 'Is there a note, feeling or practical action that needs somewhere to go?', 'What became visible: relief, grief, irritation, loneliness, nothing, or something else?'] }, landing: 'Is lack of space being created by habit, by a real structure, or by both? Would creating more room displace sleep, income, essential care or somebody else’s capacity?', positions: 'Take one realistic action; designate a time to wait; acknowledge and carry; seek practical help; leave the matter open.', support: 'The Guide does not turn structural scarcity into a scheduling failure.' }
      ]
    },
    {
      id: 'focus', number: 3, name: 'Focus', line: 'Clarity comes when you pay attention',
      entry: ['Filter helped you distinguish some of what is asking for attention. That does not mean one true priority will now appear. A grown life may contain several legitimate claims: work, care, security, freedom, health, loyalty, curiosity and rest.', 'Focus is where those claims meet a finite life. The difficult choices are often not between meaning and distraction, but between one meaning and another. A clearer choice may still hurt because something worthwhile will receive less.', 'The next chapters examine values in conflict, goals that make real claims on life, and doubt that may contain fear, humility, missing capability or misfit. The purpose is not inner alignment. It is a more truthful basis for judgement.'],
      arrival: 'Which two worthwhile claims are hardest to hold together now?',
      transition: { explored: ['You considered values that compete, a goal that would make real claims on the rest of life, and doubt that may deserve investigation without receiving authority.', 'Focus does not guarantee an easy or settled choice. It makes the terms of judgement more visible: what matters here, what this season permits, what each direction costs and which uncertainty cannot be removed in advance.'], next: 'Flow brings thought into contact with the body, time, money, responsibilities, interruptions and support actually available. Lived experience may confirm the judgement, modify it or show that the plan cannot be carried as imagined.' },
      chapters: [
        { n: 7, title: 'Defining Your Core Values', entry: ['Values do not always point in one direction. Sometimes they explain why a decision is difficult.', 'Choose one live decision that is taking more energy than its apparent size seems to require. Avoid naming one side as virtue and the other as selfishness, weakness or failure.'], primary: { kind: 'Map', title: 'Values in conflict', intro: ['Add two or three claims that genuinely matter in this decision.', 'For each possible choice, record:'], fields: ['Possible choice', 'What would this choice honour?', 'What would it cost or displace?', 'Whose cost would be most visible?', 'Whose cost has been disappearing?', 'What constraint is real?', 'Which consequence would I have to own?'], repeatable: true }, optional: { kind: 'Reflect', title: 'What three ordinary decisions show', fields: ['Choose one value you say matters and look at three recent decisions in which it was involved. What else mattered? Which claim received time, money or attention? What constraint shaped the allocation? Does an inherited value remain one you endorse now?'] }, landing: 'Has the uncertainty reduced, or has it become more accurate? Are you asking values to decide something that still requires evidence, timing or acceptance of loss?', positions: 'Make a provisional judgement; gather missing evidence; take a small expression of one value; set a review point; leave the conflict open.' },
        { n: 8, title: 'Setting Intentional Goals', entry: ['Wanting something and turning it into a goal are different acts.', 'A goal begins to organise the present around a possible future. It claims time, money, attention and sometimes other people’s cooperation. This activity does not ask whether the goal feels light or impressive. It asks what it is for and what life it would create if it worked.'], primary: { kind: 'Map', title: 'Why this, why now and why not', intro: ['For one desire or goal, respond in as much depth as needed.'], fields: ['Why this? What would it express, create or change?', 'Why now? What makes this the right season, the only possible season, or possibly the wrong one?', 'What would it displace?', 'Who else would be affected by its pursuit or success?', 'What would success require me to keep doing after the exciting part?', 'What would not pursuing it mean?', 'Is there an unlived possibility here that needs grief rather than conversion into a new target?'] }, optional: { kind: 'Try This', title: 'A goal as a six-week enquiry', fields: ['For the next six weeks, I am going to explore whether…', 'The smallest serious form of the enquiry', 'Evidence to gather about the work itself and its effect on the rest of life', 'Support or conditions needed', 'What might tell me it is time to look again?', 'What would justify continuing, revising, pausing or ending?'], experiment: true, outro: 'The review is not an excuse to stop or a promise to continue. It allows the person living the plan to report back to the person who made it.' }, landing: 'Is the desire still alive when its costs and consequences are visible? Has new information changed the season rather than invalidated the desire? Are you protecting an identity or choosing a direction?', positions: 'Begin the bounded enquiry; seek practical information; discuss the effect with someone involved; mourn an unavailable possibility; revise the goal; leave it open.' },
        { n: 9, title: 'Reframing Self-Doubt', entry: ['Doubt is neither an enemy nor a compass. It is one source of information among several.', 'Choose one recurring doubt or one decision in which hesitation matters. The aim is not to talk yourself into action. A defensible refusal may be as sound as beginning.'], primary: { kind: 'Map', title: 'What kind of doubt is this?', intro: ['Mark any that may be present and add your evidence:', 'Capability — knowledge, skill or preparation may genuinely be missing.', 'Consequence — the stakes are real and deserve thought.', 'Exposure — judgement, visibility or discovering a limit feels threatening.', 'Misfit — the opportunity or its attached life may not belong to you.'], fields: ['Which kind of doubt may be present, and what is the evidence?', 'What exactly do I predict will happen?', 'What evidence supports the prediction?', 'What evidence challenges it, including times doubt was right?', 'What can I prepare, test or ask?', 'What uncertainty will remain?', 'Is further thought still changing the evidence?'] }, optional: { kind: 'Record', title: 'How this doubt behaves over time', intro: ['Add rows only when a new episode occurs.'], fields: ['Date', 'Situation', 'First prediction', 'Action or refusal', 'What happened', 'What the doubt noticed accurately', 'What it missed'], repeatable: true, dated: true, ongoing: true }, landing: 'Is there a practical gap to address, a real consequence to accept, an uncertainty only action can answer, or evidence of misfit? Are you preparing for new information or repeating preparation to postpone exposure?', positions: 'Prepare; ask; conduct a bounded test; act with remaining uncertainty; decline; gather more episodes; leave open.' }
      ]
    },
    {
      id: 'flow', number: 4, name: 'Flow', line: 'Moving with reality, not against it',
      entry: ['Focus may have helped you see what matters and what a direction could cost. Flow asks what happens when that judgement meets Tuesday’s poor sleep, Thursday’s appointment, limited money, an unpredictable body and the people whose needs do not disappear because you made a plan.', 'This is not the stage where everything begins to move smoothly. It is where lived experience becomes evidence. Low capacity is not a character report. Rest need not repay you through productivity. Movement, pause, help, revision and ending can all be forms of progress.'],
      arrival: 'What fact about your present capacity or circumstances most needs to be included now?',
      transition: { explored: ['You looked at capacity rather than character, rest without a productivity test, and progress broad enough to include interruption, help, revision and ending.', 'Living a choice supplies evidence thinking cannot. If the plan changed, that does not by itself mean the earlier judgement was wrong. It may mean the person making it has learned what the choice asks of the life in which it must be lived.'], next: 'Rise takes developing judgement into rooms, relationships and systems containing other people’s needs, power and interpretations. You can take responsibility for your contribution without taking responsibility for the whole outcome.' },
      chapters: [
        { n: 10, title: 'Energy Economics', entry: ['The same hour can contain very different capacity. The visible task is not always the whole demand.', 'This record looks across several days. It is not a scorecard and does not require a pattern or an improvement. Record only what helps you understand the capacity that was actually present.'], primary: { kind: 'Record', title: 'A capacity map across days', fields: ['Date', 'Time or context', 'Demand or activity', 'Physical, cognitive, emotional, sensory or responsibility demand', 'How capacity felt before', 'Anticipatory or residual demand not visible on the calendar', 'How capacity felt afterwards', 'Conditions that made the same task easier or harder', 'Was the demand fixed, negotiable, shareable or optional?', 'What restored something, even if it did not restore everything?'], repeatable: true, dated: true, ongoing: true }, optional: { kind: 'Reflect', title: 'What the entries may show', fields: ['What demanded more than it appeared to?', 'Did two manageable things become costly when placed together?', 'Is a reduction, different condition, practical help, medical attention or organisational response indicated?', 'What expectation would need revision if current capacity were taken seriously?'] }, landing: 'Is the issue a pattern you can influence, a changed bodily baseline, a structural overload, a period that must be carried, or still unclear? What evidence comes from more than one day?', positions: 'Make one realistic adjustment; ask for help or redistribution; lower a standard; seek appropriate health or practical advice; continue observing; acknowledge that little can move now.' },
        { n: 11, title: 'Rest Without Earning It', entry: ['Rest is a reduction in demand. Relief is an easing of pressure. Recovery is the return of some capacity. They do not always arrive together.', 'Choose one period when rest was available but did not feel restorative, or when stopping itself was difficult. This is not a request to design an ideal routine.'], primary: { kind: 'Reflect', title: 'A rest inquiry', fields: ['What demand became smaller during the rest?', 'What demand continued: responsibility, decision-making, pain, vigilance, guilt, sensory input or something else?', 'What did I believe I should feel afterwards?', 'What actually changed, including if very little changed?', 'Was I seeking rest, relief, recovery or all three?', 'What support, cover or reduction was missing?', 'Is one realistic reduction possible at the scale of the actual problem?'] }, landing: 'Did the rest fail, or was it asked to repair more than it could? Is the obstacle permission, practical cover, money, safety, pain, insomnia, persistent exhaustion or a combination?', positions: 'Allow the rest to stand without repayment; reduce one demand; seek cover or shared responsibility; make an appointment or seek appropriate advice; leave the question open.', support: 'Persistent exhaustion, low mood, breathlessness, pain or disrupted sleep needs practical or medical attention, not another private rest technique.' },
        { n: 12, title: 'Momentum, Pauses and Endings', entry: ['Momentum is useful when it carries something that still matters. It becomes dangerous when motion supplies its own justification.', 'Progress can include a step taken, deliberate non-action, new evidence, help, a lower standard, a revised plan or an ending. This record gives all of them a place.'], primary: { kind: 'Record', title: 'A truthful progress record', intro: ['For one week or one meaningful stretch of time, add dated entries under any relevant heading.'], fields: ['Date', 'A step taken', 'A step deliberately not taken', 'New information', 'Help requested or received', 'A standard lowered', 'A plan paused, revised or ended', 'An effect on another person or commitment that needs attention'], repeatable: true, dated: true, ongoing: true }, optional: { kind: 'Reflect', title: 'When you return after interruption', fields: ['Does this still matter?', 'What changed while I was away?', 'What pace is possible now?', 'Am I returning from desire, duty, guilt or fear of wasting earlier effort?', 'What does continuation now require?', 'If I end or reduce this, what notice, transfer, repair or remaining commitment belongs to me?'] }, landing: 'Is momentum revealing reality or helping you avoid reassessment? Would stopping abandon a responsibility, end an outdated plan, or both? What consequence is avoidable and what is inherent in the decision?', positions: 'Continue; revise pace or standard; pause with a review point; seek help; prepare a responsible ending; end; leave open.' }
      ]
    },
    {
      id: 'rise', number: 5, name: 'Rise', line: 'Bringing your calm strength into the world',
      entry: ['Flow asked what your judgement could carry in the life you actually have. Rise asks what happens when it meets other people.', 'A changed decision alters what somebody else can expect. A boundary redistributes work or inconvenience. A clear contribution can be interrupted or misread. The room has power, history and assumptions before you enter it. You can prepare, speak, listen, repair and seek support. You cannot control how everyone responds.', 'The next chapters examine emotion without demanding calm, boundaries inside real relationships and power structures, and presence that includes the whole room rather than making reception a private performance problem.'],
      arrival: 'Where is your judgement now meeting a person, room or system you cannot control?',
      transition: { explored: ['You looked at emotion as information without making calm the standard, at boundaries where power and redistribution matter, and at presence as an interaction between your contribution and a room you do not control.', 'You can own intention, expression, consequence and repair without owning every reaction or the whole system. Sometimes the next work is adjustment. Sometimes it is support, distance or a judgement about what the room can offer.'], next: 'Rhythm recognises that no arrangement stays finished. Capacity, people and circumstances change. Some matters need recalibration, some need repair, and some remain part of the life without resolving.' },
      chapters: [
        { n: 13, title: 'Emotional Agility', entry: ['An emotion can contain present information, interpretation, history and bodily preparation at the same time.', 'This is not an exercise in translating every feeling into calm. Choose a recent moment that still feels relevant. The aim is a fuller account, not a more acceptable performance.'], primary: { kind: 'Map', title: 'What happened, what it meant, what followed', fields: ['What actually happened?', 'What did I understand it to mean at the time?', 'What did history or an earlier experience add?', 'What did my body and emotions do?', 'What did I do, conceal, delay or wish I had done?', 'What evidence appeared afterwards?', 'What purpose, safety or dignity mattered in the moment?', 'With the fuller account, what response seems available now?'] }, optional: { kind: 'Try This', title: 'A pause in a live moment', intro: ['Name the feeling. Notice the body without demanding that it change. Orient to what is actually happening. Choose whether to speak, ask, leave, wait or seek support. A pause counts as useful if it creates choice; the feeling does not have to reduce.'], fields: [] }, landing: 'Does the feeling need action, acknowledgement, expression, more evidence or companionship? Are you regulating yourself mainly to protect other people’s comfort? Is the response repeated or making ordinary life difficult?', positions: 'Respond now; wait; express without solving; gather evidence; speak to someone trustworthy; seek professional support; leave open.', support: 'Repeated panic, traumatic responses or persistent low mood require support beyond another private coping exercise.' },
        { n: 14, title: 'Boundaries Under Pressure', entry: ['A boundary becomes real when it meets another person’s need, expectation or authority.', 'A limit describes what you will do, accept or remain available for. It cannot control the other person’s response. More context may be respectful; repetition in search of permission may dissolve the limit. Power affects what can be said safely and what preparation is required.'], primary: { kind: 'Map', title: 'The boundary in the real relationship', fields: ['What is the limit trying to protect?', 'What responsibility remains mine?', 'What does the other person legitimately need or believe?', 'What power does each person have?', 'What work, emotion, inconvenience or risk would be redistributed?', 'What response is likely?', 'What support, documentation, advice or ally might be needed?', 'Is the aim repair, redistribution, distance or clarity?', 'Is a direct boundary safe and available here?'] }, optional: { kind: 'Reflect', title: 'What needs saying', intro: ['Draft the purpose, limit and relevant context in your own words. There is no requirement to be brief or “clean”.'], fields: ['What needs saying?', 'What will I do if the arrangement does not change?'] }, extra: { kind: 'Reflect', title: 'Repair inquiry', intro: ['Use when a necessary limit was delivered in a way that caused avoidable harm.'], fields: ['What did I do or say?', 'What impact can I recognise?', 'What explanation is relevant without excusing the impact?', 'What repair is available?', 'Does the limit itself still stand?'] }, landing: 'Is discomfort evidence about the boundary, its delivery, the redistribution it creates, or the other person’s preference for the old arrangement? Is power limiting the available route?', positions: 'Prepare; seek support or specialist advice; negotiate; state the limit; repair delivery; maintain distance; wait; leave open.', support: 'Where coercion or safety risk is present, the Guide stops being sufficient.' },
        { n: 15, title: 'Presence and Impact', entry: ['Presence is personal and relational. Preparation can help you speak clearly; the room still brings rank, history, bias and its own interests.', 'Use the before-and-after map for one interaction that matters. One incident may remain ambiguous. Repetition can change the evidence.'], primary: { kind: 'Map', title: 'Before and after the interaction', fields: ['Before: What do I know?', 'Before: What do I not know?', 'Before: What matters enough to say?', 'Before: What am I trying to make happen?', 'Before: What is the first thing that needs saying?', 'Before: What power, history or likely pattern is already in the room?', 'After: What did I intend?', 'After: What did I actually express?', 'After: What response or reception occurred?', 'After: What happened elsewhere in the room?', 'After: What belonged to my contribution?', 'After: What did not belong to me?', 'After: Is there impact to understand or repair?', 'After: Do I need to speak again, claim an interrupted point, document a pattern, seek an ally or let the matter stand?'] }, optional: { kind: 'Record', title: 'When one event may be a pattern', intro: ['Add dated rows for comparable interactions. The record gathers evidence; it does not begin with a conclusion about bias or personal failure.'], fields: ['Date', 'Context', 'Contribution', 'Reception', 'Who was heard', 'Interruption or appropriation', 'Relevant hierarchy or condition', 'What changed the outcome'], repeatable: true, dated: true, ongoing: true }, landing: 'Are you relying on intention to cancel impact, or on reception to define the whole truth? Does the evidence suggest an adjustment in preparation or delivery, a repair, a repeated room pattern, or continued uncertainty?', positions: 'Adjust; speak again; repair; document; seek an ally; judge the room differently; gather more evidence; leave open.' }
      ]
    },
    {
      id: 'rhythm', number: 6, name: 'Rhythm', line: 'Returning with wisdom, not judgement',
      entry: ['Rise brought your judgement into a world containing other people. Rhythm begins with the recognition that there is no final arrangement in which everything important stays comfortably in place.', 'You may return to a familiar question because circumstances changed, capacity altered, harm occurred, or the person living the life is no longer quite the person who made the earlier decision. Return does not erase what you learned. It adds new evidence.', 'The final chapters explore recalibration, realities that do not resolve, and modest ways to regain orientation inside an ordinary moment. Sometimes the work is adjustment. Sometimes repair. Sometimes carrying.'],
      arrival: 'What has changed: the situation, your capacity, your understanding, or something you cannot yet name?',
      transition: { explored: ['You considered recalibration when conditions or baselines change, truthful ways of carrying what does not resolve, and modest pauses that create orientation without pretending to solve the larger life.', 'Rhythm is not a state you complete. It is the recognition that fit changes while people and circumstances move. What helped once may need revision. A question may return carrying experience the first question did not have.'], next: 'The Guide ends at a Return Point, not a finish line. You may look across what you saved, name what you now see differently, or leave without drawing the work together.' },
      chapters: [
        { n: 16, title: 'Rituals of Recalibration', entry: ['Recalibration is not getting back to perfect. It is noticing what is true now and adjusting from there.', 'The same signal can mean different things under different conditions. A ritual can help and later become a rule. A previous baseline may no longer be available. Build this map from more than one kind of day and revise it when life changes.'], primary: { kind: 'Map', title: 'Your recalibration map', fields: ['Signals — How do I recognise drift: irritation, numbness, speed, indecision, physical tension or something else?', 'Likely conditions — What is happening around me when the signal appears?', 'Possible returns — What has helped: rest, information, company, solitude, movement, a boundary or practical help?', 'Support beyond me — Who or what belongs here when private adjustment is insufficient?', 'When this no longer helps or what has changed since I learned this'] , repeatable: true }, optional: { kind: 'Reflect', title: 'Three points of return', fields: ['Beginning: What condition am I beginning in?', 'Between: What must travel with me, and what can be placed somewhere for later?', 'Ending: What is unfinished, and does it belong under act, wait or carry?'] }, extra: { kind: 'Reflect', title: 'Repair route', intro: ['Use this route only if it belongs here.'], fields: ['What did I do?', 'What was its impact?', 'What explanation is relevant without becoming acquittal?', 'What repair is available?', 'What belongs to the other person to decide?'] }, landing: 'Are you returning to a previous understanding, or becoming acquainted with a changed baseline? Does the map over-rely on private regulation where information, redistribution, care or repair is needed?', positions: 'Adjust one condition; revise or release a ritual; ask for support; make repair; continue observing; accept a changed baseline provisionally; leave open.' },
        { n: 17, title: 'Living With What Does Not Resolve', entry: ['Some realities remain painful after understanding arrives.', 'You do not have to complete an exercise here. You may read, leave, write one line or return much later. Neither account below promises closure, forgiveness or relief. Use only what helps you remain truthful without making the loudest feeling of today the entire history.'], primary: { kind: 'Reflect', title: 'The finite life inquiry', fields: ['What reality am I most tempted to deny?', 'What am I trying to preserve?', 'What cost is unavoidable, and what cost can still be reduced?', 'What belongs to me to decide or repair?', 'What consequence will I need help to carry?'] }, optional: { kind: 'Reflect', title: 'What feels true now', privateAccount: true, intro: ['Write in as much or as little detail as you choose. The purpose is not acquittal.'], fields: ['What I knew then', 'What I could not know', 'What I chose and why', 'What happened', 'What I understand differently now', 'What I still do not know'] }, landing: 'Is there repair still available, responsibility that has become total control, a search for closure that is costing more than it can return, or weight that should not be carried alone?', positions: 'Save and stop; leave entirely open; return later; make a specific repair; seek companionship, practical help or professional support; decide not to reopen solely because pain returned.', support: 'You may leave this here. Nothing requires resolution today.' },
        { n: 18, title: 'Micro-Pauses and Sensory Grounding', entry: ['Use small practices for small pieces of leverage. Do not ask them to carry a problem that needs more.', 'Choose a pause that feels available. Keep your eyes open, move, use a non-body anchor or stop if a practice makes you less steady. The aim is contact with the present environment, body and choice.'], primary: { kind: 'Try This', title: 'Choose one small pause', intro: ['Let the exhale be comfortable and slightly longer than the inhale.', 'Name three things you can see, two sounds and one point of physical contact.', 'Notice the chair, floor or wall supporting you without telling yourself that you are safe if you do not know that.', 'Write the next step at the end of a task before opening the next demand.', 'Allow one minute before replying to a charged message, where the situation permits.', 'Use another sensory or environmental cue that works better for you.'], fields: ['What was happening?', 'What did I notice?', 'Did anything change? Nothing changed is valid.', 'What choice became available, if any?', 'Is there anything here that needs a response?'] }, optional: { kind: 'Record', title: 'When the small pause reveals a larger pattern', intro: ['Add a dated row when the same signal returns. The record is optional and begins only when you choose to track repetition.'], fields: ['Date', 'Situation', 'Signal', 'What the pause changed', 'What remained', 'What the repetition may warrant examining', 'Who or what could help'], repeatable: true, dated: true, ongoing: true }, landing: 'Was the pause enough for this moment? Is repetition pointing towards workload, relationship, health, safety or shared responsibility that a pause cannot change?', positions: 'Continue; wait; reply later; record the pattern; speak to someone trustworthy; seek organisational, practical or professional support; stop using this practice.' }
      ]
    }
  ],
  returnPoint: {
    title: 'The framework has an order. Life does not.',
    body: ['You began with something that deserved attention before you knew what it meant. You made room to distinguish what was present. You looked at what matters when worthwhile things compete, brought judgement into contact with actual capacity, and considered what happens when your choices meet other people and a world you cannot control. You reached Rhythm without being asked to become finished.', 'You may have made a decision. You may have decided not to make one yet. You may understand the question differently, or have found that it became more complicated when more of reality entered the frame.', 'If it helps, look across the material you chose to keep.'],
    fields: ['What do I see differently now?', 'What, if anything, do I want to keep noticing?', 'What remains unknown, unresolved or outside my control?', 'Is there a judgement I am ready to make, a judgement I am not ready to make, or a question that has changed?', 'Which stage or chapter might be useful if circumstances move again?']
  }
};
